version: 2.1

jobs:
  integration-tests:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: make -f Makefile.circleci integration-tests

  lint:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          command: make -f Makefile.circleci lint

  unit-tests:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: make -f Makefile.circleci unit-tests


workflows:
  version: 2
  pull_request:
    jobs:
      - lint:
          filters: &pull_request_filters
            branches:
              ignore: master
      - integration-tests:
          filters: *pull_request_filters
      - unit-tests:
          filters: *pull_request_filters
